### ISSUE TITLE
Desenvolvimento de um "beta" do projeto

### ISSUE THREAD

**Issue by crstyhs** [fga-eps-mds/2023.1-Moody#22]
Desenvolver um plugin que adiciona um botão que leva para 1 excel

**Comment by Rhumenigue** [comment]
O beta vai ser pelo plugin direto do chrome para uma página do google sheets? 

O google sheets tem uma API que podemos colocar no site e já pegar a minutagem do vídeo.

**Comment by crstyhs** [comment]
A beta do plugin vai ser local com um botão com redirecionamento para o google sheets

**Comment by crstyhs** [comment]
funcionalidades implementadas, trabalhando na melhora do design

**Comment by crstyhs** [comment]
feita adição do botão de redirecionamento para o moody

**Comment by crstyhs** [comment]
versão inicial finalizada
