### ISSUE TITLE
slides de apresentação release 1

### ISSUE THREAD

**Issue by crstyhs** [fga-eps-mds/2023.1-Moody#23]

**Comment by IanLucca12** [comment]
Minha parte tá feita

**Comment by IanLucca12** [comment]
https://docs.google.com/presentation/d/1FMSZZ3lnl7gi7E6uhs76gz7fUsidzMHt7ajkNNapnOU/edit?usp=sharing

**Comment by IanLucca12** [comment]
https://github.com/fga-eps-mds/2023.1-Moody/blob/main/links/apresentação%20release%201.md
