### ISSUE TITLE
adaptar o desing do botao

### ISSUE THREAD

**Issue by crstyhs** [fga-eps-mds/2023.1-Moody#40]
adaptar o estilo do botão e implementa-lo no moodle

**Comment by crstyhs** [comment]
### descrição: 
o design do botão já esta desenvolvido no figma e precisa ser adicionado no plugin

### tarefa: 
implementar o css e html no codigo do plugin

### critério de aceitação: 
O botão precisa estar presente quando o moodle é acessado e de acordo com a aparencia do figma

**Comment by gmeister18** [comment]
HTML do codigo criado
