### ISSUE TITLE
pesquisar implementação de build

### ISSUE THREAD

**Issue by crstyhs** [fga-eps-mds/2023.1-Moody#41]
pesquisar como criar uma build para o moodle

**Comment by TheCarlosRamos** [comment]
Você se refere com a Build do moodle para identificar uma versão compilada do moodle/ o sistema operacional?

**Comment by crstyhs** [comment]
Isso,uma build q execute o moodle junto com o plugin, o sistema operacional provavelmente vai ser linux, a professora quer q tenhamos uma build que no dia da apresentaçao ela instale na maquina virtual e tudo esteja pronto

**Comment by TheCarlosRamos** [comment]
Em resumo da pesquisa, para criar uma build do Moodle, você pode seguir estas etapas:
    1) Preparação do ambiente: Certifique-se de ter um ambiente de desenvolvimento adequado configurado com os requisitos do Moodle.
    2) Configuração: Crie um banco de dados vazio e configure as informações relevantes no arquivo config.php.
    3) Instalação: Acesse o URL do seu site Moodle em um navegador e siga as instruções de instalação exibidas.
    4) Personalização e configuração: Faça as configurações adicionais necessárias no Moodle de acordo com suas necessidades.
    5) Desenvolvimento: Implemente seus recursos personalizados ou modificações no código-fonte do Moodle.
    6) Testes: Certifique-se de testar suas modificações em seu ambiente de desenvolvimento.
    7) Criação da build: Empacote todos os arquivos do Moodle em um arquivo compactado, como um ZIP.
