### ISSUE TITLE
organização das pastas do github e documentação

### ISSUE THREAD

**Issue by crstyhs** [fga-eps-mds/2023.1-Moody#48]
organizar as pastas no github e checagem das documentações

**Comment by TheCarlosRamos** [comment]
Daremos direcionamento para a documentação com o relatório postmortem, o relatório técnico e a Release note

**Comment by TheCarlosRamos** [comment]
Para a postmortem, irei consultar todos os membros da equipe pois o ponto e a experiência de cada um ao longo do curso será importante

**Comment by TheCarlosRamos** [comment]
Acredito que se criarmos uma pasta "Docs" podemos colocar as documentações, o postmortem e os outros

**Comment by IanLucca12** [comment]
as pastas foram organizadas e as documentações necessárias foram feitas assim como o registro de reuniões
