### ISSUE TITLE
Entrega do texto de postmorthem

### ISSUE THREAD

**Issue by crstyhs** [fga-eps-mds/2023.1-Moody#50]
### descrição:
Um dos documentos necessários para a entrega final

### tarefa:
criar um documento descrevendo sua experiência no projeto e entregar para @TheCarlosRamos 

### critério de aceitação:
descrevam os seguintes tópicos pra eu construir o postmorthem:

- pontos positivos e negativos ao longo do projeto
- conselho para projetos futuros
- e descreva sua experiência individual no trabalho
- cite o seu papel no trabalho (Scrum Master, PO, desenvolvedor, DevOps,...)

**Comment by crstyhs** [comment]
entregue: 
- [ ] Christian
- [ ] Ian
- [ ] Carlos
- [ ] Guilherme
- [ ] Rhumenigue

**Comment by TheCarlosRamos** [comment]
Vou atualizando à medida que os membros do grupo vão intregando

**Comment by Rhumenigue** [comment]
#50 finalizado.
