### ISSUE TITLE
documentação necessária para a definição de metas

### ISSUE THREAD

**Issue by crstyhs** [fga-eps-mds/2023.1-Moody#8]
-documentação do publico alvo do projeto

-documentação dos objetivos do projeto

# Objetivos do Moody 
 

-Objetivo do bot Moody é disponibilizar relatórios com informações como o tempo de uso do moodle ,quantidade de logins e porcentagens como total de material visualizado, formulários respondidos entre outros. O intuito e agregar o máximo de informação possível para um melhor feedback de como é utilizado a turma criada pelo responsável.

**Comment by Rhumenigue** [comment]
# Objetivos do Moody 
 

-Objetivo do bot Moody é disponibilizar relatórios com informações como o tempo de uso do moodle ,quantidade de logins e porcentagens como total de material visualizado, formulários respondidos entre outros. O intuito e agregar o máximo de informação possível para um melhor feedback de como é utilizado a turma criada pelo responsável.
